'use strict';

// tests for registYesterdayViewCount
// Generated by serverless-mocha-plugin
console.log("current path", __dirname, process.cwd());
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('registYesterdayViewCount', '/functions/sqs/registYesterdayViewCount/index.js', 'handler');

describe('registYesterdayViewCount', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {

    const queueData = JSON.stringify({
      "accountId": "ymggt@naver.com",
      "documentId": "2ea2bfdc1829436da352a34d829ed172",
      "confirmViewCount": 5,
      "date": 1540425600000
    })

    const event = {
      Records: [ {
          body: queueData
        }
      ]
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
