'use strict';

// tests for qraphql
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('graphql', '/src/index.js', 'handler');

describe('CreatorSchemaTest', () => {
  before((done) => {
    done();
  });

  it('determineCreatorRoyalty', () => {
    
    const event = {
      httpMethod: "POST",
      body: JSON.stringify({
        query: `{
          Creator {
            determineCreatorRoyalty(userId:"google-oauth2|101778494068951192848", documentId:"feed7f026db54859bec3221dcad47d8f"){
              activeDate
              userId
              documentId
              pageview
              totalPageview
              royalty
            }
          }
        }`
      })
    }

    return wrapped.run(event).then((response) => {
      const body = JSON.parse(response.body)
      const r = response.statusCode === 200 && !body.errors
      expect(r).to.be.equal(true)
    });

    
  });

});
