'use strict';

// tests for qraphql
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('graphql', '/src/index.js', 'handler');

describe('Document', () => {
  before((done) => {
    done();
  });

  it('Get Document', () => {

    const query = `{
      getDocument: Document {
        findById(_id: "feed7f026db54859bec3221dcad47d8f"){
          _id
          title
          seoTitle
          desc
          isPublic
        }	
      }
    }`
    
    const event = {
      httpMethod: "POST",
      body: JSON.stringify({
        query
      })

    }


    return wrapped.run(event).then((response) => {
      const body = JSON.parse(response.body)
      console.log(JSON.stringify(body))
      const r = response.statusCode === 200 && !body.errors
      expect(r).to.be.equal(true)
    });
  });

});
