'use strict';

// tests for qraphql
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('graphql', '/src/graphql/graphql.js', 'src/graphql/graphql');

describe('graphql', () => {
  before((done) => {
    done();
  });

  it('addFavorite', () => {
    
    const event = {
      body: {
        "operationName":null, 
        "variables":{}, 
        "query": `mutation { 
          UserDocumentFavorite {addFavorite(documentId: "asdf") {
            _id
            }
          }
        }
          `}
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(res).to.not.be.empty;
    });
  });
});
