'use strict';

// tests for qraphql
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('qraphql', '/src/qraphql/graphql.js', 'src/qraphql/graphql');

describe('qraphql', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {

      const res = await graphql.graphql(
        schema,
        `query {
          getDocument: Document {
            findById(_id: "fdc219a700c344469fa076b5bbac4d08"){
              _id
              title
              seoTitle
              desc
            }	
          },
          getUser: User {
            findById(_id: "fdc219a700c344469fa076b5bbac4d08"){
              _id
              email
            }	
          },
          getDocuments: Document {
              findMany(filter: {state: CONVERT_COMPLETE, isPublic: false},
              sort: STATE__CREATED_DESC){
              _id
              state
              title
              seoTitle
              desc
              isPublic
              created
            }
          }
              
        }`
      );
      
      expect(res).to.not.be.empty;
    });
  });
});
