'use strict';

// tests for claimReward
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('claimReward', '/src/claim/reward.js', 'handler');

describe('claimReward', () => {
  before((done) => {
    done();
  });

  it('feed7f026db54859bec3221dcad47d8f implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "feed7f026db54859bec3221dcad47d8f"
      }
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });

  it('e6cf11472a174eb9ba6897136ac1b2b8 implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "e6cf11472a174eb9ba6897136ac1b2b8"
      }
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });

});
