'use strict';

// tests for createAccount
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createAccount', '/src/account/create.js', 'handler');

describe('createAccount', () => {
  before((done) => {
    done();
  });
  after((done, fn) => {
    done();
    process.exit();
  });
  it('Create Externally Owned Address (EOA), google-oauth2|101778494068951192848', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848"
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    }).catch((err)=>{
      console.log(err);
    });
  });

  it('Create Externally Owned Address (EOA), linkedin|HpIQ_mxN0N', () => {
    const event = {
      principalId: "linkedin|HpIQ_mxN0N"
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    }).catch((err)=>{
      console.log(err);
    });
  });
});
