'use strict';

// tests for getBalance
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getBalance', '/src/account/balance.js', 'handler');

describe('getBalance', () => {
  before((done) => {
    console.log("test start!!!");
    done();
  });

  after((done, fn) => {
    console.log("test complete!!");
    done();

    wrapped = undefined;
  });

  it('miner', () => {
    const event = {
      principalId: "miner"
    }

    return wrapped.run(event).then((response) => {
      console.log(response)
      expect(response).to.not.be.empty;
    });
  });

  it('google-oauth2|101778494068951192848', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848"
    }

    return wrapped.run(event).then((response) => {
      console.log(response)
      expect(response).to.not.be.empty;
    });
  });

  it('linkedin|HpIQ_mxN0N', () => {
    const event = {
      principalId: "linkedin|HpIQ_mxN0N"
    }

    return wrapped.run(event).then((response) => {
      console.log(response)
      expect(response).to.not.be.empty;
    });
  });
});
