'use strict';

// tests for requestGas
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('requestGas', '/src/gas/request.js', 'handler');

describe('requestGas', () => {
  before((done) => {
    done();
  });

  it('request gas', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848"
    }

    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  }).timeout(60000);
});
