'use strict';

// tests for walletVote
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('walletVote', '/src/wallet/vote.js', 'handler');

describe('walletVote', () => {
  before((done) => {
    done();
  });

  it('e6cf11472a174eb9ba6897136ac1b2b8 implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "e6cf11472a174eb9ba6897136ac1b2b8",
        amount: 10
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
  /*
  it('feed7f026db54859bec3221dcad47d8f implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "feed7f026db54859bec3221dcad47d8f",
        amount: 1
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
  */
});
