'use strict';

// tests for walletRegistryDoc
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('walletRegistryDoc', '/src/wallet/registryDoc.js', 'handler');

describe('walletRegistryDoc', () => {
  before((done) => {
    done();
  });

  it('feed7f026db54859bec3221dcad47d8f implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "feed7f026db54859bec3221dcad47d8f"
      }
    }
    return wrapped.run(event).then((response) => {
      const parsedRes = JSON.parse(response)
      
      if(parsedRes.success) console.log(response);

      expect(response).to.not.be.empty;
    });
  });

  it('asdfasfsadf implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "asdfasdfsf"
      }
    }
    return wrapped.run(event).then((response) => {
      const parsedRes = JSON.parse(response)
      
      if(parsedRes.success) console.log(response);

      expect(response).to.not.be.empty;
    });
  });
});
