'use strict';

// tests for schedulerWithdrawEvent
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('schedulerWithdrawEvent', '/src/scheduler/withdrawEvent.js', 'handler');

describe('schedulerWithdrawEvent', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
