'use strict';

// tests for sqsDeposit
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('sqsDeposit', '/src/sqs/deposit.js', 'handler');

describe('sqsDeposit', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      "Records": [
          {
            "body": JSON.stringify({
              "address" : "0x564323D4DeD9551CCcf69231fBEf7e5701Ab0023",
              "blockHash" : "0xe9a019a159a17ca3363cbd31d30839b03b7deb73b6db7c1e76f20602969c36d9",
              "blockNumber" : 5346782,
              "logIndex" : 7,
              "removed" : false,
              "transactionHash" : "0x2210c452b34c6de5a29b004c15fc17e7888b60db60d1367fa1a68725cc864c9c",
              "transactionIndex" : 3,
              "id" : "log_7f27e64d",
              "returnValues" : {
                "0" : "0x4Ee128892469e7962e6E617727cb99C59525D7D2",
                "1" : "0x07Ab267B6F70940f66EAf519b4a7c050496480D3",
                "2" : "10000000000000000000",
                "from" : "0x4Ee128892469e7962e6E617727cb99C59525D7D2",
                "to" : "0x07Ab267B6F70940f66EAf519b4a7c050496480D3",
                "value" : "10000000000000000000"
              },
              "event" : "Transfer",
              "signature" : "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
              "raw" : {
                "data" : "0x0000000000000000000000000000000000000000000000008ac7230489e80000",
                "topics" : [
                  "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                  "0x0000000000000000000000004ee128892469e7962e6e617727cb99c59525d7d2",
                  "0x00000000000000000000000007ab267b6f70940f66eaf519b4a7c050496480d3"
                ]
              }
            })
          }
      ]
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });

    
  }).timeout(30000);
});
