'use strict';

// tests for eventWithdraw
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('sqsWithdraw', '/src/sqs/withdraw.js', 'handler');

describe('sqsWithdraw', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
        "Records": [
          {
              "body": JSON.stringify({
                "id": "asdfasfdsa",
                "toAddress":"0xa05b51311397C5552798Ce216250BC0e757c1Aa2",
                "value":"1000000000000000000"
              })
          }
        ]
    }
    
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
