'use strict';

// tests for pdfConvertComplete
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('pdfConvertComplete', '/src/document/pdfConvertComplete.js', 'handler');

describe('pdfConvertComplete', () => {
  before((done) => {
    done();
  });

  it('pdf', () => {
    const event = {
      "Records": [
        
        {
          "s3": {
            "bucket": {
              "name": "dev-ca-document",
            },
            "object": {
              "key": "PDF/c64bfec0add949e280de9db670f43331/c64bfec0add949e280de9db670f43331.pdf"
            }
          }
        }
        
      ]
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });

  it('base64 encoded pdf', () => {
    const event = {
      "Records": [
        
        {
          "s3": {
            "bucket": {
              "name": "dev-ca-document",
            },
            "object": {
              "key": "PDF/c64bfec0add949e280de9db670f43331/c64bfec0add949e280de9db670f43331"
            }
          }
        }
        
      ]
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
