'use strict';

// tests for s3DocumentUploadComplete
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('s3DocumentUploadComplete', '/src/document/uploadComplete.js', 'handler');

describe('s3DocumentUploadComplete', () => {
  before((done) => {
    done();
  });

  

  it('upload complete document ppt 229257c8085145008268cbd2ba146dc5', () => {
    const event = {
      "Records": [
        {
          "s3": {
            "bucket": {
              "name": "dev-ca-document"
            },
            "object": {
              "key": "FILE/google-oauth2|101778494068951192848/229257c8085145008268cbd2ba146dc5.pptx",
            }
          }
        },
      ]
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
