'use strict';

// tests for s3DocumentUploadComplete
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('s3DocumentUploadComplete', '/src/document/uploadComplete.js', 'handler');

describe('s3DocumentUploadComplete', () => {
  before((done) => {
    done();
  });

  

  it('[ASEM] upload complete', () => {
    const event = {
      "Records": [
        {
          "s3": {
            "bucket": {
              "name": "asem-ko-document"
            },
            "object": {
              "key": "FILE/google-oauth2|101778494068951192848/022f3acc6b05484cb787032c81fc304d.pdf",
            }
          }
        },
      ]
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  }).timeout(30000);
});
