'use strict';

// tests for IndexLambda
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('IndexLambda', '/src/indexLambda.js', 'handler');

describe('IndexLambda', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {

    const event = {
      "Records": [
        {
          "cf": {
            "config": {
              "distributionId": "default"
            },
            "request": {
              "uri": "/dean123/global-logistics-network-powerpoint-templates1-ss78i31"
            }
          }
        }
      ]
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });
});
