'use strict';

// tests for completeConvert
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('completeConvert', '/src/completeConvert.js', 'handler');

describe('completeConvert', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      "Records": [
        {
          "s3": {
            "bucket": {
              "name": "asem-ca-upload-document"
            },
            "object": {
              "key": "THUMBNAIL/98af37649f554903aa9837eff72b1aa0/1200X1200/1"
            }
          }
        },
        {
          "s3": {
            "bucket": {
              "name": "asem-ca-upload-document"
            },
            "object": {
              "key": "THUMBNAIL/98af37649f554903aa9837eff72b1aa0/1200X1200/2"
            }
          }
        }, 
        {
          "s3": {
            "bucket": {
              "name": "asem-ca-upload-document"
            },
            "object": {
              "key": "THUMBNAIL/98af37649f554903aa9837eff72b1aa0/result.txt"
            }
          }
        }, 
        {
          "s3": {
            "bucket": {
              "name": "asem-ca-upload-document"
            },
            "object": {
              "key": "THUMBNAIL/98af37649f554903aa9837eff72b1aa0/text.json"
            }
          }
        },
      ]
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
