'use strict';

// tests for requestConvert
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('requestConvert', '/src/requestConvert.js', 'handler');

describe('requestConvert', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      "Records": [
        {
          "s3": {
            "bucket": {
              "name": "asem-ca-upload-document"
            },
            "object": {
              "key": "FILE/google-oauth2|101778494068951192848/98af37649f554903aa9837eff72b1aa0.pdf",
            }
          }
        },
      ]
    }

    return wrapped.run(event).then((response) => {
      
      expect(response).to.not.be.empty;
    });
  });
});
