'use strict';

// Generated by serverless-mocha-plugin
// TODO: sls invoke test
// TODO: sls invoke test [--stage stage] [--region region] [-f function1] [-f function2] [...]
console.log("current path", __dirname, process.cwd());
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('cronDepositDocument', '/functions/sqs/cronDepositDocument/index.js', 'handler');

describe('cronDepositDocument', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    //ae5bb91da55142f1b6aa038c04266c8c, 40cca9f5e8f34449bdaebe7516d9bdd7
    const records = [ { messageId: 'f9a6985d-03be-476a-a97b-12f0dab3dc07',
                        receiptHandle: 'AQEBrk/UMYHQJ6dDksNLxUvCV2PaSnk7nhO7AAC5Ld0uPvssxcOq8Tmq4gXt7rU0VRtccmgfo7U5QNE1EN6BMVM2Kth+2pYC1WPcrlIjcnzQ3W5jJLdwoiIqJ771BBOLhUnEemVFTV7m01wAFEkN0ssKRwORgvIpiki6UdUQFVusb0MLlfFqnoqgjl/h7N6/1aC3/6XRRoPR0FdmmWQCaFqDOJapZIGnlU38QymssaTTzlFXzDwPZxH8Hydm5/Fd1pBiFMVyrj8kD/KBAEAf8KFKPVeJFgs+zpENTfXAKQ9rIKu7MvmeDfpuilCkji33X7bEYGNspf5eDiGmRsudNRs9DVhEjfz81y+sbQ7L0oBmBm7MXWSF9TZTsTM42yD390LBs9yplw95rh0Noq8k/EeYnVWH1lHhHCiXvlYQjWVz1aY=',
                        body: '{"accountId":"0xc9464264562c0288d6A7d714573cC451b95ac35c","documentId":"eded52894dd249f4a678dae0a2e77301","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421315',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '92fe5f71f9102105df98a5acc2e818e9',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: '5ba618a0-c503-4350-8430-03467ca95ddd',
                        receiptHandle: 'AQEBO0Xf0trZqUYlKsu6VxPTuhau48TMQcuT8dZMVf+mYMi7t5bV9ax0k7Xl7RY4toGlv8wGG1yXsFMOf6lE21OoY+kYDNxL1ECVbRT72gb41RNkpnyOB6Q5+l9h3cThhW5fzx76AMvsfbm+H6WJKUSoq8pe3sFM8Gfa6g4bxtwEO/szyoILX/LPdSof+ndkr6O7pl9sL1s6bnROTw0Bw3NTQnbVnH8dSG3FvW8b97Bs97DkC01IwuVs8c3Cqs1Ybdm+cQzUmbKmjg2ep1vk+PmTRds841CVciljR9GLXR3YudyNUU23KOyW96hAAuu2Mwqm/XRqCi0XFXZs2zj+Hy4cM2TF0zxC5LjXmgdw7DurkVTLGOuQWbRBazeTVnFAn33uhjY67vw/o1/NXj52Foc55HtAt0zy1Kvqb+sjsh3rgtc=',
                        body: '{"accountId":"0xc9464264562c0288d6A7d714573cC451b95ac35c","documentId":"7d3f2698915246f3bd6759ae4a1a54aa","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421319',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '135358f6659e588076619a9a585ad707',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: 'e81c27e7-75fe-42ac-8694-2145eb7018a3',
                        receiptHandle: 'AQEBcmvhAPluT4nmwjNskjSbIO0xcNIOGDF66mMD/0Uymm0OLpuoghgboC3tnAtLd2ICU1//dJ9EKRPa8bZy52lshIrRGGr9TtxzjbHUS8PkyA68Wf0mYO1hHkh1tKZbkt+464A8fRaJIQmTaIrZAlO47oqCaNO5dvuUSIWHa53pcldkCsN/lzDWbT6oE+/K1s8xhtd3pb4el+hgVQiFgTjmla30KU/06LQKFkew13wKG6qm4L/1PrXTp9kvoRvp1C/W+S9zyCMeQ2wUy3hhqySoeyqcYflbWgYvx1CHMbqhSlC+MGXYOoW/bMl2A0w70/U4P5yn428DY7zTW/DnvOGKueJuIlSAzTr9e7Fz/Y1dI9rMGFxV+kbTIaVlpmXucod5BCNJRvhP4nBWRVE2SbtDSWJXFKpcX6ZgjOdMR49yRG4=',
                        body: '{"accountId":"0x3A543305049d735602fB747B69afeC08e8C6a58C","documentId":"510fad34d012473190bd3d744b258671","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421383',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: 'fdb45b7d56207ed9bbad6e6fcdbcfc2f',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: 'f523ef61-eb18-488b-8467-580a63e5ba0c',
                        receiptHandle: 'AQEB8AmccHRLs3MlXmbyCoo07RzIIam7EQvCScxPNRaM/onlITNvIRsH1v7eYBjhMeudjrPTNlL+QIdgPQoI03qifHNj+6aKK9f9K5G7bM2EEh/fi4JFYpFQ7xJz6Y7nLZLmlN0H5z2OEngD6vdf++PhtuP0+ko8wV5NbWDtqYmFGq+43MjKFPVwCP8NwADOFhXk1NDQJ/BmqKFNW9NFUYhJBaKv0inq/NLocPWwXKoD+81ObEFbc5D8/EaNYIehkawTgA+fZdK4ETZgD12ui813YTBfCOWW+Jk27f9wc0uzMXvqHKVwpH8Z2KqSfXd4EeqJmuTdbMQsFgZwjZK7YWUKlk60dCPaxKs5r4C2XorRp/OLQ4Js8fm67by0ESm4KvMUHMwAy2J1jHJhyvL2+g2EgQaLQz6Oi/k8Ji92TaodKvU=',
                        body: '{"accountId":"0xD722d24DFEBaE890aA8218D4045b9c6442Ca1c3d","documentId":"f21c0a9ff9f14cee80fd310997a6985a","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421533',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '2c71e686f7d1233b11c668ea353f6b34',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: '0f1871a1-ae9d-4c34-a531-dcfd8747eef4',
                        receiptHandle: 'AQEBth0nbZJChKh2IWKO+OgZ6nqiGu2SDWbEMSx02vfWbEmg/Ti/GX4EgQ0tkn+MPQCkMOUYUKy3xwcOltxOz7vjliV7ZW7wrr2/r4gP8MW3PUCtnX7zv86VGBLPK9LP/cpYWuz/l9mTff460rJwZwql2T0T0UuNR7h3lcycPJe3leDMLmogf/zxgrvhGKsbJy52ksmFsbzXZgqmpmpNOYdoozP5bTpOGapZF/uwMI7JIR/E+qg3wNiB4fkOjEvopf9XhEWQQ0Vpi02vQYY/kSr772Ltean4PTQXEyYo75ZImEBwMZwx2RKNB7dPQ8cfd6qc76pn/+/AWagEXrjiaEkei6eoPr3yJzrgs4M4c2w3w5k2KUOKFXgrNH0LL/F5uC7Xp3B12NFyhLSOYjsEV/ZBAJarvzzwgHcMgybT5OxJybE=',
                        body: '{"accountId":"0xD722d24DFEBaE890aA8218D4045b9c6442Ca1c3d","documentId":"b828ca3701854c749c25ab92bf468336","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421555',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '357625b5a2f82bc16fd137cf2d15b314',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: 'c4ee1f94-24fe-45f0-b2e1-76c0ad482320',
                        receiptHandle: 'AQEBlbIvv+TKz4PKQZFkkaMoUi17se0cue/UXZbC1hjeJnx2pTeX+y3QBE2nak8v1OwrGA4P+ap2XqVNRK7qQnMPwkR/7oToNQGoSbyYPT5L/9kVkh3bZE4M10zcaaT86i1L0W84AKSzyElvJj1FIJHJQvD1NJi7NQmknSHxMyMVoQadLYKMd7lmkmBNwp9QiyEz0JmaQyt3XLt50oQHM15h4aIXpdFZJhpXyz3veQdY9YXY3eHb8Rge5184bHjjL0wSVAwD/nCSxdT8w0pKbvmuF4pbaMPU3XaJrPkoKabKnpsvx7B6YAfs8mLoDT3ohUg+YePzDcd4ede9b1iDxCr5TDfuflpUZziScY5EM3Izd7YUMppH5QQBobOgE/RzOty8QFrvCAAhdXRzOvNNipQLCrEE06G1JjcX2RJA1yqFIk8=',
                        body: '{"accountId":"0x0b267e594b0Fa1E50dF323654Dd6802Cc6CfBA2D","documentId":"917d4097052a4fba907de77aba1157d2","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421570',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '555ef95ea6a1d0c72ea02507ee645728',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: '1c91e8d2-10c8-428c-9cfc-d0e5515ac0a5',
                        receiptHandle: 'AQEBApa1qb4n+vpqSi1b7K8eXUFTsZU3NTAjf+UL+JeVAADRJsyC0NrVyg7J+ITqFCDUR73iYOslSWpFgJqsnlf+g6fjULNEZ9ShiqAhF5iV7DDlU+Lqw/CEgyI5hPWTHYRttSC0ckaPAXPwMyr06TFucY5duFo1z4YoClSdUDIkS9TeEhlcE2TcQe/6gI+A4vIfEd7xJtfwutkKoRdWRy/v6S+vKxWJQGmGzEnJPf/SsBN4Z2c9BVEEmdAHhRkAumYywvsdcLXfq1FxATATSC/6o2jQGE/eJHj/F2jxChgAtgFOLc3GKSoquKN3ZcctL/Pk8TXIRnD8MfxoSw+oHL/2N40UB6tzcauowUPCMquYNbXVXochC4rjaqCYovbd2PKyyyH1qrN1Wt5H1kWdKNlJPIsMblIRchMWHqf9C92GUG8=',
                        body: '{"accountId":"0x274C6d3516D14f7314B4D62aBE895EA13A404Ba1","documentId":"b636ead28357482b9e498e652a82cbda","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421636',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '1b91db388457abab48690be37ac5bdea',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: '698030d2-5552-4f1c-a519-73ef50e4c9a2',
                        receiptHandle: 'AQEB6Eevz4to8VDFi+j9VMBER7E3iXcPhBlREN/OYBg6cR9yCoodWBP2SNoes9lYSBKg9KwBQrUMK3NYG/UNZkmVeZctsiHUKnhatDBFF8Ue9pZ2QfjvCExmJQh4ENUX1sW2C+Cu4ipR6FGIV9gIN1d+fPtHhNr3gxBybEC2nGTYXkjs6l6r8vx6kAwbBtio08DMvCfvW6nTvLeyqXXC+8FXOi/8nDvdMeHKA7LcV92vp+p1zEQRLp8lWjxbyirgdNm+pubTF4HuR+GFVV1c2DhuCo+BwFmPTkRKuGn7lPgxdcmfEpkiLjO3lBDfK/Cdaz7W6KQmi7quty1PKqtAp2SSVYjp1/IP9gFd0faXz6yqfhTVb7Q8DXnh9zrEVXGNgAasmJOKwYUiwZaxfJQijwjj6cBsd6ZuJO83FWuLB4kNi4I=',
                        body: '{"accountId":"0x274C6d3516D14f7314B4D62aBE895EA13A404Ba1","documentId":"e871c81be7da4f18b1d5b4388fcdb27e","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421675',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '7fe7c650c8a09bbb37f2264156212832',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: 'a1e88708-6573-4436-93ea-e087336cd46e',
                        receiptHandle: 'AQEB9j8aF9IDFyC6TIP/VAHf8phun6kqrv9+0Z7yNwt535dbizenzjrW321oylWvx287ZATn3k2Z/XnQGASaSi6sSHRuMei5I0Dp3Qoe61CD7Aao0C1kYZ2v05MvFxrm83NA4aMZqpyRoIY3vQtYLOAgW6fmnvj+RJ5HpKrN2YW9gOeTapbQNjhuCdwrxuc8jZAGgi7k7kvFtl6PiuyTwPIPuqkNkGP2lBdkRnjIj+ghxYQbLQXLtSohZgj6amK0Q99JN8doyKhQ/9i45yXLotj4aDqrpR4vYdoMexGJ0YDbVwcVW1MLo3dLXHuBrOS3d9fKITXUC753V3Axjp+sKNDOP4vtrAbJW3aP+rQUcY8qumXpkVwJaiaphaFV0jc+PFfA3p511+RY5OUMsFH0zcRHAX0qXYJlCJUO5NyPyt2dbYI=',
                        body: '{"accountId":"0xa824ff038F371e28344F330f5c59d036E66dD989","documentId":"3c9d4a0274ec4fdfae41bedf08fd40b9","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421714',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '8e9a418eb8352d4d7f3c652bfd5de930',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' },
                        { messageId: 'fe74283e-8825-4100-a600-068ce2cb4ab8',
                        receiptHandle: 'AQEBme9+RlnOpyu3FY/1zGVEnBIGfVK4a34IVKLWFNyiYroqkbGPeKqchAEPWxp8632B/CXXqWYIsmH9U/vcPJre96JnATKq5sB8v6/kRIYcVKhcB/FFbMKrAv90j3yp4DPZpqjU61LDulEN9RJU8yD90tVjhopVlmmWh3mj+JMeF+9gtLyjO7M8LfXiJJyD8e+wB5bJTjREX3cB4Pbd64LjIASNME6euozZWL5ysCkmIjcslf+yAhhqqBrKjK73p+b/krCDZXVodC3Vg6xxuSvn//djIKgIcz1Ch+Shx45Xl2M6NJ+cjSouDUfS6/FO3b3cG9KvsBgZtzVgKMDUgCCwMXJewOE83laRornkDuV7EOR3lMDZU1xhnCB/287Kw0NsT+O2ORLwD3ina/jHpEm4c9iM760AZ+68nm+xPGV31BY=',
                        body: '{"accountId":"0xa824ff038F371e28344F330f5c59d036E66dD989","documentId":"e942e0323875463f9ba368bc39716967","requestId":"5dcbe760-e601-11e8-901b-6180745d615c"}',
                        attributes:
                        { ApproximateReceiveCount: '1',
                        SentTimestamp: '1541975421755',
                        SenderId: 'AROAJ2WIHRNA77OE627DC:CronAuthorConfirmReward',
                        ApproximateFirstReceiveTimestamp: '1541975424210' },
                        messageAttributes: {},
                        md5OfBody: '0be0cde5a69b5ecea0821ea8d0ef3373',
                        eventSource: 'aws:sqs',
                        eventSourceARN: 'arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-AUTHORCONFIRMREWARD',
                        awsRegion: 'us-west-1' } ];

    const event = {
      Records: records
    }


    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
