'use strict';

// tests for registYesterdayViewCount
// Generated by serverless-mocha-plugin
console.log("current path", __dirname, process.cwd());
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('registYesterdayViewCount', '/functions/sqs/registYesterdayViewCount/index.js', 'handler');

describe('registYesterdayViewCount', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    //ae5bb91da55142f1b6aa038c04266c8c, 40cca9f5e8f34449bdaebe7516d9bdd7
    const queueData = JSON.stringify({
      "accountId": "ymggt@naver.com",
      "documentId": "ae5bb91da55142f1b6aa038c04266c8c",
      "confirmViewCount": 5,
      "date": 1540857600000,
      });


    const queueData2 = {
      "accountId": "ymggt@naver.com",
    "documentId": "40cca9f5e8f34449bdaebe7516d9bdd7",
    "confirmViewCount": 104,
    "date": 1540857600000 }

    const event = {
      Records: [ {
          body: queueData
        }
      ]
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
