'use strict';

// tests for accountGet
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('accountGet', '/controllers/account/get', 'handler');

describe('accountGet', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      
    }
    return wrapped.run(event).then((response) => {
      console.log("response", response);
      expect(response).to.not.be.empty;
    });
  });
});
