'use strict';

// tests for analyticsExport
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('analyticsExport', '/controllers/analytics/export.js', 'handler');

describe('analyticsExport', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      query: {
        documentId: "5bab09df70ed4307aad667300fc0c95c",
        week: 1
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
