'use strict';

// tests for analyticsList
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('analyticsList', '/controllers/analytics/list.js', 'handler');

describe('analyticsList', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      query: {
        documentId: "6e1e0b4e86824eba81e9350a0fd1ff82",
        week: 32
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
