'use strict';

// tests for registYesterdayViewCount
// Generated by serverless-mocha-plugin
console.log("current path", __dirname, process.cwd());
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('ContractInfo', '/functions/contract/contractInfo/index.js', 'handler');

describe('registYesterdayViewCount', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {



    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
