'use strict';

// tests for curatorSummary
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('curatorSummary', '/controllers/curator/curatorSummary.js', 'handler');

describe('curatorSummary', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      query: {
        ethAccount: "0xCb58C536d3C32C06e1c0Ffa442952841eCDdeeda"
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
