'use strict';

// tests for curatorDocumentList
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('curatorDocumentList', '/controllers/curator/curatorDocumentList.js', 'handler');

describe('curatorDocumentList', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      body: {
        pageNo: 1,
        accountId: "0xf319E1a032338183c4fDC024F3e3845497dB3152"
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
