'use strict';

// tests for curatorDocumentList
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('curatorDocumentList', '/controllers/curator/curatorDocumentList.js', 'handler');

describe('curatorDocumentList', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      query: {
        pageNo: 1,
        ethAccount: "0x4add6551af429c71eB64e0494BC5E88334E94948"
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
