'use strict';

// tests for documentMeta
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('documentMeta', '/controllers/document/documentMeta.js', 'handler');

describe('documentMeta', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      query: {
        seoTitle: "free-ppt-template-3rsjwy"
      }
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
