'use strict';

// tests for documentPDF
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('documentPDF', '/controllers/document/documentPDF.js', 'handler');

describe('documentPDF', () => {
  before((done) => {
    done();
  });

  it('get pdf stream base64', () => {
    const event = {
      query: {documentId : "07637479b9874749a7e723fe949d3dad"}
    }
    return wrapped.run(event).then((response) => {
      console.log(response.pdf);
      expect(response.success === true && response.pdf!== undefined).to.be.true;
    });
  });
});
