'use strict';

// tests for documentDownload
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('documentDownload', '/controllers/document/documentDownload.js', 'handler');

describe('documentDownload', () => {
  before((done) => {
    done();
  });

  it('get download url', () => {
    const event = {
      query: {documentId : "c4bd778acdc24992a7da9bc57262c536"}
    }
    return wrapped.run(event).then((response) => {
      const res = JSON.parse(response);
      expect(res.success === true && res.downloadUrl!== undefined).to.be.true;
    });
  });
});
