'use strict';

// tests for documentUpdate
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('documentUpdate', '/controllers/document/documentUpdate.js', 'handler');

describe('documentUpdate', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "968de024dd1647f1a7544d9c4b46de48",
        title: "ethereum yellowpaper",
        isDownload: true,
        useTracking: true,
        forceTracking: false
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
