'use strict';

// tests for documentUpdate
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('documentUpdate', '/controllers/document/documentUpdate.js', 'handler');

describe('documentUpdate', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      principalId: "google-oauth2|101778494068951192848",
      body: {
        documentId: "5bab09df70ed4307aad667300fc0c95c",
        //title: "SolidWorks Introduction~~" + Date.now(),
        isDownload: false,
        useTracking: false,
        forceTracking: false
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
