'use strict';

// tests for documentUpdate
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('documentInfo', '/controllers/document/documentController.js', 'info');

describe('documentInfo', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      path: {
        //documentId: "dev-test-ovobik"
        documentId: "free-ppt-template-3rsjwy"
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
