'use strict';

// tests for embededDocument
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('oembedDocument', '/controllers/oembed/oembedDocument.js', 'handler');

describe('oembedDocument', () => {
  before((done) => {
    done();
  });

  it('404 landscape doc', () => {
    const event = {
      query: {
        url: encodeURIComponent("https://share.decompany.io/jayjayjay/ethereum-yellowpaper-3xlv2m/")
      }
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });


  it('landscape doc', () => {
    const event = {
      query: {
        url: encodeURIComponent("https://share.decompany.io/dean123/global-logistics-network-powerpoint-templates1-ss78i3")
      }
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });

  it('portrait doc', () => {
    const event = {
      query: {
        url: encodeURIComponent("https://share.decompany.io/jayjayjay/uunio-3cife5/")
      }
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });

  it('landscape doc', () => {
    const event = {
      query: {
        url: encodeURIComponent("https://share.decompany.io/dean123/2019-medical-plan-powerpoint-templates-skcn9t/")
      }
    }
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });

});
