'use strict';

// tests for s3DocumentUploadComplete
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('s3DocumentUploadComplete', '/s3/document/uploadComplete.js', 'handler');

describe('s3DocumentUploadComplete', () => {
  before((done) => {
    done();
  });

  const event = {
    "Records": [
      {
        "s3": {
          "bucket": {
            "name": "dev-ca-document"
          },
          "object": {
            "key": "FILE/google-oauth2%7C101778494068951192848/f67795af03af44b18a92f4a273bbe5b1.pdf",
          }
        }
      },
    ]
  }

  it('implement tests here', () => {
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
