'use strict';

// tests for tagList
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('tagList', '/controllers/tag/list.js', 'handler');

describe('tagList', () => {
  before((done) => {
    done();
  });

  it('latest', () => {

    return wrapped.run({
      query: {
        t: 'latest'
      }
    }).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
