'use strict';

// tests for trackingConfirm
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('trackingConfirm', '/controllers/tracking/confirm.js', 'handler');

describe('trackingConfirm', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {body: {
      documentId: "3a328b4a0c8e4638b7c110ecb791bbce",
      email: "worn29@gmail.com"
    }}
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
