'use strict';

// tests for trackingList
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('trackingList', '/controllers/tracking/list.js', 'handler');

describe('trackingList', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {query: {
      documentId: "3a328b4a0c8e4638b7c110ecb791bbce",
      include: false,
      anonymous: false
    }}

    return wrapped.run(event).then((response) => {
      console.log("response!!");
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });
});
