'use strict';

// tests for trackingList
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('trackingList', '/controllers/tracking/list.js', 'handler');

describe('trackingList', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {query: {
      documentId: "00065c0b528f415a830f50b1c16c8e66"
    }}

    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  });
});
