'use strict';

// tests for trackingExport
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('trackingCollect', '/controllers/tracking/collect.js', 'handler');

describe('trackingCollect', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {

    const event = {
      
    }
    return wrapped.run().then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
