'use strict';

// tests for trackingConfirm
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('trackingConfirm', '/controllers/tracking/confirm.js', 'handler');

describe('trackingConfirm', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {body: {
      documentId: "00065c0b528f415a830f50b1c16c8e66",
      email: "worn29@gmail.com",
      cid: "1060212880.1546915423",
      sid: "XkUaGxvrE"
    }}
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
