'use strict';

// tests for trackingList
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('trackingList', '/controllers/tracking/list.js', 'handler');

describe('trackingList', () => {
  before((done) => {
    done();
  });

  it('exclude anonymous user, 1page ', () => {
    const event = {
      query: {
        documentId: "feed7f026db54859bec3221dcad47d8f",
        include: false,
        anonymous: false
      }
    }

    return wrapped.run(event).then((response) => {
      //console.log("response!!");
      //console.log(response);
      expect(response).to.not.be.empty;
    });
  });

  it('include anonymous user, exclude 1 page doc', () => {
    const event = {
      query: {
        documentId: "feed7f026db54859bec3221dcad47d8f",
        include: false,
        anonymous: true
      }
    }

    return wrapped.run(event).then((response) => {
      //console.log("response!!");
      //console.log(response);
      expect(response).to.not.be.empty;
    });
  });

  it('include anonymous user, 1 page doc', () => {
    const event = {
      query: {
        documentId: "feed7f026db54859bec3221dcad47d8f",
        include: true,
        anonymous: true
      }
    }

    return wrapped.run(event).then((response) => {
      //console.log("response!!");
      //console.log(response);
      expect(response).to.not.be.empty;
    });
  });
});
