'use strict';

// tests for zapierEmail
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('zapierEmail', '/controllers/zapier/email.js', 'handler');

describe('zapierEmail', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      query: {
        documentId: "5bab09df70ed4307aad667300fc0c95c"
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
