'use strict';

// tests for customSearch
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('customSearch', '/src/google/customSearch.js', 'handler');

describe('customSearch', () => {
  before((done) => {
    done();
  });

  it('Context Search', () => {

    const event = {
      queryStringParameters: {
        q: "decompany"
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });

  it('Image Search', () => {

    const event = {
      queryStringParameters: {
        q: "decompany",
        searchType: "image"
      }
    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
