'use strict';

// tests for eventWithdraw
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('sqsWithdraw', '/src/sqs/withdraw.js', 'handler');

describe('sqsWithdraw', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
        "Records": [
            {
                "messageId": "059f36b4-87a3-44ab-83d2-661975830a7d",
                "receiptHandle": "AQEBwJnKyrHigUMZj6rYigCgxlaS3SLy0a...",
                "body": JSON.stringify({
                  from: "0x07Ab267B6F70940f66EAf519b4a7c050496480D3",
                  to: "0x4Ee128892469e7962e6E617727cb99C59525D7D2",
                  value: 10
                })
            }
        ]
    }
    
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
