'use strict';

// tests for pageviewRequestPutOnChainByDaily
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('dailyPageview', '/functions/cron/dailyPageview.js', 'handler');

describe('dailyPageview', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    
    //2019. 10. 29 ~ 2019. 10. 30
    let event ={
      start: Date.UTC(2019, 9, 30),
      end : Date.UTC(2019, 9, 31)
    };
    
    return wrapped.run(event).then((response) => {
      console.log(response);
      expect(response).to.not.be.empty;
    });
  }).timeout(300000);
});
