'use strict';

// tests for onchainWritePageview
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('onchainWritePageview', '/functions/onchain/writePageview.js', 'handler');

describe('onchainWritePageview', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {

    const event = {
      Records:[
        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3",
            date: 1550620800000,
            confirmPageview: 32
          })
        }
      ]
    }
    return wrapped.run(event).then((response) => {
      console.log("Test Complete", response)
      expect(response).to.not.be.empty;
    })
  }).timeout(300000);
});
