'use strict';

// tests for pageviewByHourly
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('pageviewByHourly', '/functions/cron/hourly.js', 'handler');

describe('pageviewByHourly', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  }).timeout(300000);;
});
