'use strict';

// tests for pageviewCollector
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('pageviewCollector', '/functions/cron/pageviewCollector.js', 'handler');

describe('pageviewCollector', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      console.log("test case response", response)
      expect(response).to.not.be.empty;
    });
  }).timeout(300000);
});
