'use strict';

// tests for onchainWritePageview
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('pageviewWriteOnchain', '/functions/onchain/pageviewWriteOnchain.js', 'handler');

describe('pageviewWriteOnchain', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {

    const event = {
      Records:[{
        body: JSON.stringify({
          blockchainTimestamp: 1555286400000,
          count: 14,
          unit: 10000,
          endIndex: 0,
          index: 0
        })
      }]
    }

    return wrapped.run(event).then((response) => {
      console.log("Test Complete", response)
      expect(response).to.not.be.empty;
    })
  }).timeout(300000);
});
