'use strict';

// tests for readLatestCreatorReward
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('readLatestCreatorReward', '/functions/onchain/readLatestCreatorReward.js', 'handler');

describe('readLatestCreatorReward', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {

    const event = {
      Records:[
        {
          body: JSON.stringify({
            documentId: "c4754f829e8f48d7a737e9e5ac592885",
            blockchainTimestamp: 1552435200000
          })
        },
        
        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3"
          })
        },
        /*
        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3"
          })
        },

        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3"
          })
        },

        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3"
          })
        },

        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3"
          })
        },

        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3"
          })
        },

        {
          body: JSON.stringify({
            documentId: "28aa48c287a141868243360dffcda4a3"
          })
        }
        */
      ]
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
