'use strict';

// tests for s3AggregationPageView
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('s3AggregationPageView', '/s3/aggregation/pageview.js', 'handler');

describe('s3AggregationPageView', () => {
  before((done) => {
    done();
  });

  
  it('implement tests here', () => {

    const event = {
      "Records": [
        {
          "s3": {
            "bucket": {
              "name": "dev-ca-document",
              "ownerIdentity": {
                "principalId": "A3C4A60J8BI88N"
              },
              "arn": "arn:aws:s3:::dev-ca-document"
            },
            "object": {
              "key": "viewcount/2018-10-18/004c938c-sdfas-sdf-asdf-sadf.csv",
              "size": 1476706,
              "eTag": "1c1cb937280f8607f05a4fa86a1bc441",
              "sequencer": "005BEB690CE5C89929"
            }
          }
        }
      ]
    }

    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
