const utils = require('./src/utils');
const s3Utils = require('./src/s3Utils');
const mongoWrapper = require('./src/MongoWrapper');
const firehose = require('./src/kinesisFirehose');
const kinesis = require('./src/kinesis');
const sqs = require('./src/sqs');
const kms = require('./src/kms');
const ses = require('./src/ses');
const cloudfront = require('./src/cloudfront');
const sns = require('./src/sns');

module.exports.utils = utils;
module.exports.s3 = s3Utils;
module.exports.MongoWapper = mongoWrapper;
module.exports.MongoWrapper = mongoWrapper;
module.exports.firehose = firehose;
module.exports.kinesis = kinesis;
module.exports.sqs = sqs;
module.exports.kms = kms;
module.exports.ses = ses;
module.exports.cloudfront = cloudfront;
module.exports.sns = sns;
module.exports.CacheWrapper = require('./src/CacheWrapper')