'use strict';

// tests for verifyEmailRequest
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('verifyEmailRequest', '/src/email/verifyEmailRequest.js', 'handler');

describe('verifyEmailRequest', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      headers: {
        Referer: "https://share.decompany.io/aboutus/xxxxxxx"
      },
      body: {
        email: "abc@gmail.com",
        re: "jay@decompany.io",
        ts: Date.now()
      }

    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
