'use strict';

// tests for verifyEmail
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('verifyEmail', '/src/email/verifyEmail.js', 'handler');

describe('verifyEmail', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    const event = {
      headers: {
        Referer: "https://share.decompany.io/aboutus/xxxxxxx"
      },
      path: {
        code: "b003ed3fbbbb1d043dd3f275abac518c82ea5f97"
      }

    }
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
